Repository YAPP-Github/21st-iOS-Team-1-BE, pull requests merged in 2023-02, with the labels that each got.

#23 Feat : Global, Business 예외처리 로직 적용
  YAPP-BE/src/main/java/yapp/common/oauth/controller/AuthController.java
  YAPP-BE/src/main/java/yapp/common/oauth/service/AuthService.java
  YAPP-BE/src/main/java/yapp/common/oauth/token/AuthTokenProvider.java
  YAPP-BE/src/main/java/yapp/domain/member/controller/MemberController.java
  YAPP-BE/src/main/java/yapp/domain/member/repository/MemberRepository.java
  YAPP-BE/src/main/java/yapp/domain/member/service/MemberService.java
  YAPP-BE/src/main/java/yapp/exception/GlobalExceptionHandler.java
  YAPP-BE/src/main/java/yapp/exception/TokenValidFailedException.java
  YAPP-BE/src/main/java/yapp/exception/base/BusinessException.java
  YAPP-BE/src/main/java/yapp/exception/base/InvalidInputException.java
  YAPP-BE/src/main/java/yapp/exception/base/member/MemberException.java
  YAPP-BE/src/main/java/yapp/exception/model/ErrorCodes.java
  YAPP-BE/src/main/java/yapp/exception/model/ErrorResponse.java
Labels: For: Utils, Type: Feature

#27 Feat: 동네 인프라/테마 장소 조회 API 개발
  YAPP-BE/build.gradle
  YAPP-BE/src/main/java/yapp/common/config/Const.java
  YAPP-BE/src/main/java/yapp/common/config/QueryDslConfig.java
  YAPP-BE/src/main/java/yapp/common/config/SecurityConfig.java
  YAPP-BE/src/main/java/yapp/common/domain/Location.java
  YAPP-BE/src/main/java/yapp/domain/townMap/controller/TownMapController.java
  YAPP-BE/src/main/java/yapp/domain/townMap/converter/LocationConverter.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/InfraPlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/LocationInfoResponse.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/ThemePlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/entity/Infra.java
  YAPP-BE/src/main/java/yapp/domain/townMap/entity/Place.java
  YAPP-BE/src/main/java/yapp/domain/townMap/entity/Theme.java
  YAPP-BE/src/main/java/yapp/domain/townMap/repository/InfraRepository.java
  YAPP-BE/src/main/java/yapp/domain/townMap/repository/PlaceRepository.java
  YAPP-BE/src/main/java/yapp/domain/townMap/repository/PlaceRepositoryCustom.java
  YAPP-BE/src/main/java/yapp/domain/townMap/repository/PlaceRepositoryImpl.java
  YAPP-BE/src/main/java/yapp/domain/townMap/repository/ThemeRepository.java
  YAPP-BE/src/main/java/yapp/domain/townMap/service/TownMapService.java
Labels: Tag: 동네지도, For: API, Type: Feature

#29 Refactor: 동네 좌표 조회 API 로직 추가
  YAPP-BE/src/main/java/yapp/domain/townMap/controller/TownMapController.java
  YAPP-BE/src/main/java/yapp/domain/townMap/service/TownMapService.java
Labels: Tag: 동네지도, For: API, Type: Refactor

#30 Feat: 동네 찾기 필터 기능
  YAPP-BE/src/main/java/yapp/common/config/Const.java
  YAPP-BE/src/main/java/yapp/common/config/QueryDslConfig.java
  YAPP-BE/src/main/java/yapp/common/config/SecurityConfig.java
  YAPP-BE/src/main/java/yapp/domain/member/dto/MemberAccountDto.java
  YAPP-BE/src/main/java/yapp/domain/town/comparator/TownComparator.java
  YAPP-BE/src/main/java/yapp/domain/town/controller/TownController.java
  YAPP-BE/src/main/java/yapp/domain/town/converter/TownConverter.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/TownDto.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/request/TownFilterRequest.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/response/TownFilterResponse.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/FilterStatus.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Infra.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/InfraStatus.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Mood.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Place.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Subway.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/SubwayStatus.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Town.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownMood.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownPopular.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownSubway.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepository.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepositoryImpl.java
  YAPP-BE/src/main/java/yapp/domain/town/service/TownService.java
Labels: For: API, Type: Feature, Tag: 동네찾기

#33 Feat: 동네 소개페이지 상세 조회 API
  YAPP-BE/build.gradle
  YAPP-BE/src/main/java/yapp/common/config/SecurityConfig.java
  YAPP-BE/src/main/java/yapp/domain/town/controller/TownController.java
  YAPP-BE/src/main/java/yapp/domain/town/converter/TownConverter.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/TownDetailDto.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/response/TownFilterResponse.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/response/TownInfoResponse.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Place.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Subway.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownHotPlace.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownSubway.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepository.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepositoryImpl.java
  YAPP-BE/src/main/java/yapp/domain/town/service/TownService.java
  YAPP-BE/src/main/java/yapp/domain/townMap/controller/TownMapController.java
  YAPP-BE/src/main/java/yapp/domain/townMap/service/TownMapService.java
  YAPP-BE/src/main/java/yapp/exception/base/town/TownException.java
Labels: For: API, Type: Feature, Tag: 동네 소개페이지

#34 Feat: 동네 찾기 (구 별) 검색 API
  YAPP-BE/src/main/java/yapp/domain/town/controller/TownController.java
  YAPP-BE/src/main/java/yapp/domain/town/converter/TownConverter.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/request/TownSearchRequest.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/response/TownSearchResponse.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepository.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepositoryImpl.java
  YAPP-BE/src/main/java/yapp/domain/town/service/TownService.java
Labels: For: API, Type: Feature, Tag: 동네찾기

#36 Feat: 동네 찜 등록/해제 API
  YAPP-BE/src/main/java/yapp/domain/member/controller/MemberController.java
  YAPP-BE/src/main/java/yapp/domain/member/entitiy/MemberWishTown.java
  YAPP-BE/src/main/java/yapp/domain/member/repository/MemberWishTownRepository.java
  YAPP-BE/src/main/java/yapp/domain/member/service/MemberService.java
Labels: For: API, Type: Feature, Tag: 동네 찜

#39 Refactor: 동네지도 인프라/테마지도 장소 조회 response 수정
  YAPP-BE/src/main/java/yapp/domain/member/entity/Member.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/MemberPrincipal.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/MemberRefreshToken.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/MemberWishTown.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/Resident.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/WishStatus.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/YN.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/InfraPlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/ThemePlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/entity/Place.java
Labels: Tag: 동네지도, For: API, Type: Refactor

#42 Refactor: access_token 재발행 로직, 동네 필터, 소개 API 수정
  YAPP-BE/src/main/java/yapp/common/oauth/controller/AuthController.java
  YAPP-BE/src/main/java/yapp/domain/member/repository/MemberRefreshTokenRepository.java
  YAPP-BE/src/main/java/yapp/domain/town/converter/TownConverter.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/TownDetailDto.java
  YAPP-BE/src/main/java/yapp/domain/town/dto/response/TownInfoResponse.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/FilterStatus.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Mood.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Subway.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/SubwayStatus.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Town.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownHotPlace.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepositoryImpl.java
  YAPP-BE/src/main/java/yapp/domain/town/service/TownService.java
Labels: For: API, Type: Refactor, Tag: 동네 필터링, Tag: 동네 소개페이지

#45 Feat: 마이페이지 닉네임 수정 및 회원 탈퇴 기능
  YAPP-BE/src/main/java/yapp/common/oauth/controller/AuthController.java
  YAPP-BE/src/main/java/yapp/common/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  YAPP-BE/src/main/java/yapp/common/oauth/service/AuthService.java
  YAPP-BE/src/main/java/yapp/common/oauth/service/CustomOAuth2UserService.java
  YAPP-BE/src/main/java/yapp/common/oauth/service/CustomUserDetailsService.java
  YAPP-BE/src/main/java/yapp/common/repository/LocationRepository.java
  YAPP-BE/src/main/java/yapp/domain/member/controller/MemberController.java
  YAPP-BE/src/main/java/yapp/domain/member/converter/MemberConverter.java
  YAPP-BE/src/main/java/yapp/domain/member/dto/request/MemberSignUpRequest.java
  YAPP-BE/src/main/java/yapp/domain/member/dto/response/MemberInfoResponse.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/Member.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/MemberPrincipal.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/MemberRefreshToken.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/MemberWishTown.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/Resident.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/WishStatus.java
  YAPP-BE/src/main/java/yapp/domain/member/entity/YN.java
  YAPP-BE/src/main/java/yapp/domain/member/repository/MemberRefreshTokenRepository.java
  YAPP-BE/src/main/java/yapp/domain/member/repository/MemberRepository.java
  YAPP-BE/src/main/java/yapp/domain/member/repository/MemberWishTownRepository.java
  YAPP-BE/src/main/java/yapp/domain/member/service/MemberService.java
  YAPP-BE/src/main/java/yapp/domain/town/converter/TownResidentConverter.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Town.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownResident.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepositoryImpl.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownResidentRepositroy.java
  YAPP-BE/src/main/java/yapp/domain/townMap/service/TownMapService.java
Labels: For: API, Type: Feature, Tag: 마이페이지

#48 Refactor: 동네지도 인프라/테마지도 장소 조회 API response 수정
  YAPP-BE/src/main/java/yapp/domain/member/controller/MemberController.java
  YAPP-BE/src/main/java/yapp/domain/townMap/converter/PlaceConverter.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/InfraPlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/ThemePlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/InfraPlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/InfraPlaceResponse.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/ThemePlaceDto.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/ThemePlaceResponse.java
  YAPP-BE/src/main/java/yapp/domain/townMap/repository/PlaceRepositoryCustom.java
  YAPP-BE/src/main/java/yapp/domain/townMap/repository/PlaceRepositoryImpl.java
  YAPP-BE/src/main/java/yapp/domain/townMap/service/TownMapService.java
Labels: Tag: 동네지도, For: API, Type: Refactor

#50 Refactor: 회원가입 요청시 access, refresh 토큰 발급으로 수정, 회원 정보 조회시 예외처리 로직 추가
  YAPP-BE/src/main/java/yapp/common/oauth/controller/AuthController.java
  YAPP-BE/src/main/java/yapp/common/oauth/provider/AuthProvider.java
  YAPP-BE/src/main/java/yapp/common/oauth/service/AuthService.java
  YAPP-BE/src/main/java/yapp/domain/member/controller/MemberController.java
  YAPP-BE/src/main/java/yapp/domain/member/converter/MemberConverter.java
  YAPP-BE/src/main/java/yapp/domain/member/dto/response/LocationInfo.java
  YAPP-BE/src/main/java/yapp/domain/member/dto/response/MemberInfoResponse.java
  YAPP-BE/src/main/java/yapp/domain/member/service/MemberService.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/TownResident.java
Labels: For: API, Type: Refactor, Tag: 마이페이지

#58 Feat: Application 실행 시 거주자 통계 데이터 분석후 동네 데이터 설명란 추가
  YAPP-BE/src/main/java/yapp/YappBeApplication.java
  YAPP-BE/src/main/java/yapp/common/domain/ResidentStatistics.java
  YAPP-BE/src/main/java/yapp/common/repository/LocationRepository.java
  YAPP-BE/src/main/java/yapp/common/repository/ResidentStatisticsRepository.java
  YAPP-BE/src/main/java/yapp/common/service/ResidentStatisticsService.java
  YAPP-BE/src/main/java/yapp/domain/town/entity/Town.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownRepository.java
Labels: For: Utils, Type: Feature

#61 Feat: 찜 리스트 조회 API
  YAPP-BE/src/main/java/yapp/domain/member/controller/MemberController.java
  YAPP-BE/src/main/java/yapp/domain/member/converter/MemberWishTownConverter.java
  YAPP-BE/src/main/java/yapp/domain/member/dto/MemberWishTownDto.java
  YAPP-BE/src/main/java/yapp/domain/member/service/MemberService.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepository.java
  YAPP-BE/src/main/java/yapp/domain/town/repository/TownCustomRepositoryImpl.java
Labels: For: API, Type: Feature, Tag: 동네 찜

#63 Fix: 찜 등록/해제 API 새로운 동네 등록 시 오류 수정
  YAPP-BE/src/main/java/yapp/domain/member/controller/MemberController.java
  YAPP-BE/src/main/java/yapp/domain/member/service/MemberService.java
Labels: For: API, Type: Error/Bugs, Tag: 동네 찜

#66 Refactor: 동네 좌표 조회 API response 사용자의 찜 여부 정보 추가
  YAPP-BE/src/main/java/yapp/domain/member/repository/MemberWishTownRepository.java
  YAPP-BE/src/main/java/yapp/domain/townMap/controller/TownMapController.java
  YAPP-BE/src/main/java/yapp/domain/townMap/converter/LocationConverter.java
  YAPP-BE/src/main/java/yapp/domain/townMap/dto/response/LocationInfoResponse.java
  YAPP-BE/src/main/java/yapp/domain/townMap/service/TownMapService.java
Labels: Tag: 동네지도, For: API, Type: Refactor
